context.modules = [
    { name = libpipewire-module-loopback
        args = {
            node.description = "System"
            capture.props = { media.class = Audio/Sink node.name = "System" node.description = "System" audio.position = [ FL FR ] }
            playback.props = { node.name = "System_playback" audio.position = [ FL FR ] stream.dont-remix = true }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Musik"
            capture.props = { media.class = Audio/Sink node.name = "Musik" node.description = "Musik" audio.position = [ FL FR ] }
            playback.props = { node.name = "Musik_playback" audio.position = [ FL FR ] stream.dont-remix = true }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Spil"
            capture.props = { media.class = Audio/Sink node.name = "Spil" node.description = "Spil" audio.position = [ FL FR ] }
            playback.props = { node.name = "Spil_playback" audio.position = [ FL FR ] stream.dont-remix = true }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Kommunikation"
            capture.props = { media.class = Audio/Sink node.name = "Kommunikation" node.description = "Kommunikation" audio.position = [ FL FR ] }
            playback.props = { node.name = "Kommunikation_playback" audio.position = [ FL FR ] stream.dont-remix = true }
        }
    }
]
